defaults: &defaults
  instagram_client_id: "b635452fdd1a415a825710d080b412f3"
  instagram_client_secret: "75b0ed7cce3444a2b7616593a4acac2f"
  instagram_access_token: "1924930591.b635452.abff643bd5894ba1a3f973c891ff1446"
  default_image_search_tag: "UVic"
  # If populated, the next three fields will appear at the end of page titles as "application_name - division_name - organization_name"
  application_name: "Your base app page title"
  division_name: "Division Name"
  division_url: "http://example.com/division_url"
  organization_name: "University name"
  meta_description: "A short description to include in the meta description tag"
  base_image_file_dir: "/path/to/directory/where/images/will/be/harvested"
  donor_agreement_text: "The text for your donor agreement that will be submitted as a comment"
  contact_email: "my_project@example.com"
  feed_description: "Description of this feed"
  # Uncomment to enable Google Analytics tracking
  # google_analytics_tracker: "UA-XXXXXXXX-XX"

development:
  <<: *defaults
  # Add or override config options here

test:
  <<: *defaults
  # Add or override config options here

staging:
  <<: *defaults
  # Add or override config options here

production:
  <<: *defaults
  # Add or override config options here
